### ISSUE TITLE
Invalid option in docker-compose.yml

### ISSUE THREAD

**Issue by woodonggyu** [oasis-open/cti-taxii-server#151]
Hello.

When i tested, It wasn't work.
that's because is invalid option in docker-compose.

I fixed it like this:

```
# Use root/example as user/password credentials
# You may need to change the client uri to a format like ~> mongodb://user:pass@host:port/
# Mongo Express provides a simple lightweight web administrative interface for mongoDB
version: '3'
services:
  medallion:
    build:
      context: .
      dockerfile: docker_utils/Dockerfile
    command: [sh, -c, "medallion --host 0.0.0.0"]
    environment:
      MEDALLION_BACKEND_MODULE_CLASS: "MongoBackend"
      MEDALLION_BACKEND_MONGO_URI: "mongodb://root:example@mongo:27017/"
    ports:
      - 5000:5000
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_HOST: mongo
      MONGO_PORT: 27017
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ENABLE_ADMIN: "true"
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
    depends_on:
      - mongo
```
